# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 790105c04fcb16cc4fd28e1ebfe3d688c94cee70cd94ac305c786062dcc404dc1ac91536fbd0dc70dadc90ea833d43faf1c32bbde3afbeb493f461c3396d335b

test:
  secret_key_base: 2e7c80d24128772fdbcf8d4f04ab459ab66b5332dbea2fdfd56c6191997605421472b85e2984c82281ddd2f12c3dc9c9ae644d7580db3e373eaf6348d26271ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
